version: "3.9"
volumes:
  static:
services:
  shopify-service:
    build: .
    environment:
      - PG_NAME=wisdb
      - PG_PASSWORD='wisdb_user'
    ports:
      - 8000:8000 
    env_file:
      - .env  


